export const GALLERYPRODUCT_LIST_REQUEST = "GALLERYPRODUCT_LIST_REQUEST";
export const GALLERYPRODUCT_LIST_SUCCESS = "GALLERYPRODUCT_LIST_SUCCESS";
export const GALLERYPRODUCT_LIST_FAIL = "GALLERYPRODUCT_LIST_FAIL";

export const GALLERYPRODUCT_DETAILS_REQUEST = "GALLERYPRODUCT_DETAILS_REQUEST";
export const GALLERYPRODUCT_DETAILS_SUCCESS = "GALLERYPRODUCT_DETAILS_SUCCESS";
export const GALLERYPRODUCT_DETAILS_FAIL = "GALLERYPRODUCT_DETAILS_FAIL";

export const GALLERYPRODUCT_CREATE_REQUEST = "GALLERYPRODUCT_CREATE_REQUEST";
export const GALLERYPRODUCT_CREATE_SUCCESS = "GALLERYPRODUCT_CREATE_SUCCESS";
export const GALLERYPRODUCT_CREATE_FAIL = "GALLERYPRODUCT_CREATE_FAIL";
export const GALLERYPRODUCT_CREATE_RESET = "GALLERYPRODUCT_CREATE_RESET";

export const GALLERYPRODUCT_UPDATE_REQUEST = "GALLERYPRODUCT_UPDATE_REQUEST";
export const GALLERYPRODUCT_UPDATE_SUCCESS = "GALLERYPRODUCT_UPDATE_SUCCESS";
export const GALLERYPRODUCT_UPDATE_FAIL = "GALLERYPRODUCT_UPDATE_FAIL";
export const GALLERYPRODUCT_UPDATE_RESET = "GALLERYPRODUCT_UPDATE_RESET";


export const GALLERYPRODUCT_DELETE_REQUEST = 'GALLERYPRODUCT_DELETE_REQUEST';
export const GALLERYPRODUCT_DELETE_SUCCESS = 'GALLERYPRODUCT_DELETE_SUCCESS';
export const GALLERYPRODUCT_DELETE_FAIL = 'GALLERYPRODUCT_DELETE_FAIL';
export const GALLERYPRODUCT_DELETE_RESET = 'GALLERYPRODUCT_DELETE_RESET';
